name: Run C# Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: csharp-test-run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and run tests
      run: dotnet test
